apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  fileServerUsername: {{ .Values.fileServer.username | b64enc }}
  fileServerPassword: {{ .Values.fileServer.password | b64enc }}
