apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: TYPESENSE_DATA_DIR
              value: {{ .Values.volumeClaim.path }}
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: apiKey
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
          ports:
            - name: http
              containerPort: 8108
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
          volumeMounts:
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-data
              mountPath: {{ .Values.volumeClaim.path }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-{{ .Chart.Name }}-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.volumeClaim.storageClassName }}
        storageClassName: {{ .Values.volumeClaim.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.volumeClaim.size }}
