databaseName: postgres
username: postgres
password: postgres

serviceType: ClusterIP

image:
  repository: postgres
  tag: 16.3-bullseye

volumeClaim:
  storageClassName: ""
  storage: 10Gi

resources:
  requests:
    memory: 1Gi

serviceAnnotations: {}

maxConnections: 100
sharedBuffers: "128MB"
effectiveCacheSize: "4096MB"
effectiveIoConcurrency: 10
seqPageCost: 1.0
randomPageCost: 4.0
cpuTupleCost: 0.01
