databaseName: postgres
username: postgres
password: postgres

serviceType: ClusterIP

image:
  repository: postgres
  tag: 16.3-bullseye

volumeClaim:
  storageClassName: ""
  storage: 10Gi

resources:
  requests:
    memory: 1Gi

serviceAnnotations: {}
