apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name- }}-{{ .Values.configChecksum }}-job-config
immutable: true
data:
{{- range $.Values.jobFiles }}
  {{ .name }}:
    |-
{{ .value | indent 4 }}
{{- end }}
