apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  {{- if .Values.maplibreJson }}
  maplibre.json: |-
{{ .Values.maplibreJson | indent 4 }}
  {{- end }}
  settings.json: |-
{{ .Values.settings | toJson | indent 4 }}
