apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          {{- if .Values.maplibreJson }}
          volumeMounts:
            - name: {{ .Release.Name }}-mnt
              mountPath: /app/web/maplibre.json
              subPath: maplibre.json
            - name: {{ .Release.Name }}-mnt
              mountPath: /app/settings.json
              subPath: settings.json
          {{- end }}
          resources:
            requests:
              memory: {{ .Values.resources.memoryRequest }}
            limits:
              memory: {{ .Values.resources.memoryLimit }}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 30
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 30
            periodSeconds: 30
      volumes:
       - name: {{ .Release.Name }}-mnt
         configMap:
           name: {{ .Release.Name }}
           items:
          {{- if .Values.maplibreJson }}
           - key: maplibre.json
             path: maplibre.json
          {{- end }}
           - key: settings.json
             path: settings.json
      imagePullSecrets:
        - name: {{ .Values.imgPullSecret }}
      restartPolicy: Always
