apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-danish-address-seed
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        spec:
          containers:
            - name: danish-address-seed
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              resources:
                requests:
                  memory: {{ .Values.requests.memoryRequest }}
                limits:
                  memory: {{ .Values.requests.memoryLimit }}
              env:
                - name: CONNECTION_STRING
                  valueFrom:
                    secretKeyRef:
                      key: connectionString
                      name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
              imagePullPolicy: IfNotPresent
          restartPolicy: {{ .Values.restartPolicy }}
