apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
data:
  connectionString: {{ .Values.connectionString | b64enc }}
  typesenseApiKey: {{ .Values.typesense.apiKey | b64enc }}
