image:
  repository: daxgrid/address-change-indexer
  tag: v0.6.10

resources:
  memoryRequest: 2.75Gi
  memoryLimit: 3.0Gi

appsettings:
  settings:
    eventStoreConnectionString: ""
    geoDatabaseConnectionString: ""
