kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-database-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  {{ if .Values.volumeClaim.storageClassName }}
  storageClassName: {{ .Values.volumeClaim.storageClassName }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.volumeClaim.storage }}
