apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.sqliteWeb.serviceType }}
  ports:
    - port: {{ .Values.sqliteWeb.port }}
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}
