version: 2.1

executors:
  helm-kubectl:
    docker:
    - image: dtzar/helm-kubectl

jobs:
  package-and-upload:
    executor: helm-kubectl
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "a7:ff:54:2c:7f:d0:7f:d5:ba:c6:65:28:60:f3:59:2b"
      - run:
          name: key-scan
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: git clone charts
          command: git clone git@github.com:DAXGRID/charts.git
      - run:
          name: git clone tippecanoe-chart
          command: git clone git@github.com:DAXGRID/dax-charts.git
      - run:
          name: package and push
          command: |
             cd ./charts
             helm package ../dax-charts/dax/*
             helm repo index ./ --url https://daxgrid.github.io/charts/
             git config user.email "admin@dax.dk"
             git config user.name "dax-bot"
             git add .
             git commit -m "adds/updates dax-charts - $(date --utc)"
             git push
workflows:
  package-and-upload-chart:
    jobs:
      - package-and-upload:
          filters:
            branches:
              only:
                - master
