apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pgbouncer-config
data:
  {{- if .Values.config.ssl.enabled }}
  root.crt: |-
{{ .Values.config.ssl.root | indent 4 }}
  server.crt: |-
{{ .Values.config.ssl.cert | indent 4 }}
  server.key: |-
{{ .Values.config.ssl.key | indent 4 }}
  {{- end }}
  pgbouncer.ini: |
    [databases]
    {{- range $.Values.config.databases }}
    {{ .name }} = host={{ .host }} port={{ .port }} dbname={{ .name }}
    {{- end }}

    [pgbouncer]
    listen_port = 6432
    listen_addr = {{ .Values.config.listenAddress }}
    auth_type = {{ .Values.config.authType }}
    auth_file = userlist.txt
    admin_users = {{ .Values.config.adminUsers }}

    # In case of auth type hba, we enable the pg_hba settings.
    {{- if eq .Values.config.authType "hba" }}
    auth_hba_file = pgbouncer-config/pg_hba.conf
    {{- end }}

    # Needed otherwise it fails when trying to connect.
    # https://github.com/bitnami/containers/issues/25394
    ignore_startup_parameters = extra_float_digits

    {{- if .Values.config.ssl.enabled }}
    client_tls_sslmode = prefer
    client_tls_key_file = pgbouncer-config/server.key
    client_tls_cert_file = pgbouncer-config/server.crt
    client_tls_ca_file = pgbouncer-config/root.crt
    {{- end }}

  # In case of auth type hba, we enable the pg_hba settings.
  {{- if eq .Values.config.authType "hba" }}
  pg_hba.conf: |
    {{- range $.Values.hba }}
    {{ .type}} {{ .database }} {{ .user }} {{ .address}} {{ .method }}
    {{- end }}
  {{- end }}
