apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-userlist-secret
data:
  userlist.txt: |
    {{- $lines := list -}}
    {{- range .Values.userlist -}}
    {{- $lines = append $lines (printf "\"%s\" \"%s\"" .name .password) -}}
    {{- end -}}
    {{ join "\n" $lines | b64enc }}
