apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-userlist-secret
data:
  userlist.txt: |
    {{- $userlist := "" }}
    {{- range $.Values.userlist }}
    {{- $userlist = printf "\"%s\" \"%s\"\n%s" .name .password $userlist  }}
    {{- end }}
    {{ $userlist | b64enc }}
