image:
  repository: daxgrid/cimflow-qa-overview
  tag: v5.11.0

imgPullSecret: regcred

replicas: 1

port: 80
serviceType: ClusterIP

resources:
  memoryRequest: 1Gi
  memoryLimit: 1.25Gi

settings:
  fileServer:
    uri: ""
    name: ""
    password: ""
  extractPath: ""
  username: ""
  password: ""
