apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
spec:
  schedule: "{{ .Values.schedule }}"
  startingDeadlineSeconds: 30
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              resources:
                requests:
                  memory: {{ .Values.resources.memoryRequest }}
                limits:
                  memory: {{ .Values.resources.memoryLimit }}
              volumeMounts:
                - name: {{ .Chart.Name }}-volume
                  mountPath: /app/appsettings.json
                  subPath: appsettings.json
          volumes:
            - name: {{ .Chart.Name }}-volume
              secret:
                secretName: {{ .Chart.Name }}-secret
                items:
                - key: appsettings
                  path: appsettings.json
          restartPolicy: {{ .Values.restartPolicy }}
