apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
data:
  fileServerPassword: {{ .Values.fileServer.password | b64enc }}
  appsettings: |-
{{ .Values.appsettings | toJson | b64enc | indent 4 }}
