apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  postgisPassword: {{ .Values.postgis.password | b64enc }}
  eventStoreConnectionString: {{ .Values.eventStore.connectionString | b64enc }}
