replicas: 1
serviceType: NodePort

image:
  repository: daxgrid/frontend
  tag: v8.79.2

desktopBridgeUri: ""
apiGatewayHttpUri: ""
apiGatewayWsUri: ""
keyCloakUri: ""

routeNetworkTileServerUri: ""
aerialPhotoServerUri: ""
basemapTileServerUri: ""

colorMarkings:
  - Blue
  - Red
  - Green

layers: {}

informationControlConfig: {}

maplibreJson: ""

defaultUserLanguage: "en"

initialUserPrompt: {}

tags: {}

defaultWorkTaskStatus: {}

alwaysIncludedWorkTaskTypes: {}
