apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
data:
  kafkaPositionConnectionString: {{ .Values.kafka.positionConnectionString | b64enc }}
  typesenseApiKey: {{ .Values.typesense.apiKey | b64enc }}
