apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
data:
  typesenseApiKey: {{ .Values.typesense.apiKey | b64enc }}
  eventStoreConnectionString: {{ .Values.eventStore.connectionString | b64enc }}
