apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          requests:
            memory: {{ .Values.resources.memoryRequest }}
          limits:
            memory: {{ .Values.resources.memoryLimit }}
        volumeMounts:
          - name: {{ .Chart.Name }}-volume
            mountPath: /app/appsettings.json
            subPath: appsettings.json
      volumes:
        - name: {{ .Chart.Name }}-volume
          secret:
            secretName: {{ .Chart.Name }}-secret
            items:
            - key: appsettings
              path: appsettings.json
      restartPolicy: Always
