apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-account
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            requests:
              memory: {{ .Values.resources.memoryRequest }}
            limits:
              memory: {{ .Values.resources.memoryLimit }}
          ports:
            - containerPort: 8080
          env:
            - name: JOBOVERVIEW_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: username
            - name: JOBOVERVIEW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: password
          args: ["{{ .Values.customerName }}", "$(JOBOVERVIEW_USERNAME)", "$(JOBOVERVIEW_PASSWORD)" ]
      imagePullSecrets:
        - name: {{ .Values.imgPullSecret }}
      restartPolicy: Always
