apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      volumes:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Chart.Name }}
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-secret-volume
          secret:
            secretName: {{ .Release.Name }}-{{ .Chart.Name }}-secret
            items:
            - key: ghfs-config
              path: ghfs-config
        - name: {{ .Release.Name }}-fcn-secret-volume
          secret:
            secretName: {{ .Release.Name }}-fcn-secret
            items:
            - key: appsettings
              path: appsettings.json
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            requests:
              memory: {{ .Values.resources.memoryRequest }}
            limits:
              memory: {{ .Values.resources.memoryLimit }}
          ports:
            - containerPort: 80
          command: ["/ghfs"]
          args: ["--config", "/ghfs-config"]
          volumeMounts:
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-data
              mountPath: {{ .Values.storage.path }}
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-secret-volume
              mountPath: /ghfs-config
              subPath: ghfs-config
        - name: {{ .Release.Name }}-fcn-sidecar
          image: {{ .Values.fileWatcher.image }}:{{ .Values.fileWatcher.tag }}
          resources:
            requests:
              memory: {{ .Values.fileWatcher.resources.memoryRequest }}
            limits:
              memory: {{ .Values.fileWatcher.resources.memoryLimit }}
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 15
            periodSeconds: 15
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 15
            periodSeconds: 15
          volumeMounts:
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-data
              mountPath: {{ .Values.storage.path }}
            - name: {{ .Release.Name }}-fcn-secret-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
      restartPolicy: Always
