apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-config
data:
  postgresql.conf: |
    listen_addresses = '*'

    dynamic_shared_memory_type = posix

    timezone = 'Etc/UTC'

    lc_messages = 'en_US.utf8'
    lc_monetary = 'en_US.utf8'
    lc_numeric = 'en_US.utf8'
    lc_time = 'en_US.utf8'

    default_text_search_config = 'pg_catalog.english'

    {{- if .Values.effectiveCacheSize }}
    effective_cache_size = {{ .Values.effectiveCacheSize }}
    {{- end }}

    {{- if .Values.maxConnections }}
    max_connections = {{ .Values.maxConnections }}
    {{- end }}

    {{- if .Values.sharedBuffers }}
    shared_buffers = {{ .Values.sharedBuffers }}
    {{- end }}

    {{- if .Values.effectiveIoConcurrency }}
    effective_io_concurrency = {{ .Values.effectiveIoConcurrency }}
    {{- end }}

    {{- if .Values.seqPageCost }}
    seq_page_cost = {{ .Values.seqPageCost }}
    {{- end }}

    {{- if .Values.randomPageCost }}
    random_page_cost = {{ .Values.randomPageCost }}
    {{- end }}

    {{- if .Values.cpuTupleCost }}
    cpu_tuple_cost = {{ .Values.cpuTupleCost }}
    {{- end }}
