apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-config
data:
  postgresql.conf: |
    listen_addresses = '*'

    dynamic_shared_memory_type = posix

    timezone = 'Etc/UTC'

    lc_messages = 'en_US.utf8'
    lc_monetary = 'en_US.utf8'
    lc_numeric = 'en_US.utf8'
    lc_time = 'en_US.utf8'

    default_text_search_config = 'pg_catalog.english'
