apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
spec:
  backoffLimit: {{ .Values.backoffLimit }}
  template:
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            requests:
              memory: {{ .Values.resources.memoryRequest }}
            limits:
              memory: {{ .Values.resources.memoryLimit }}
          volumeMounts:
            - name: {{ .Release.Name }}-appsettings-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
            - name: {{ .Release.Name }}-specifications-volume
              mountPath: /specifications
      volumes:
        - name: {{ .Release.Name }}-appsettings-volume
          secret:
            secretName: {{ .Release.Name }}-appsettings-secret
            items:
            - key: appsettings
              path: appsettings.json
        - name: {{ .Release.Name }}-specifications-volume
          configMap:
            name: {{ .Release.Name }}-specifications-cm
      restartPolicy: Never
  backoffLimit: 0
