image:
  repository: daxgrid/user-edit-history
  tag: v0.4.5

resources:
  memoryRequest: 500Mi
  memoryLimit: 600Mi

appsettings:
  settings:
    eventStoreConnectionString: ""
    connectionString: ""
