apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.storage.className }}
  storageClassName: {{ .Values.storage.className }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
