apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
data:
  geoDatabasePassword: {{ .Values.geoDatabase.password | b64enc }}
  eventStoreDatabasePassword: {{ .Values.eventStoreDatabase.password | b64enc }}
